<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>b40812f3-64e0-4b90-ac59-51a9e41b3ede</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Garnet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CacheInvalidation.WebApi\CacheInvalidation.WebApi.csproj" />
  </ItemGroup>

</Project>
