<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <!-- Test names are sentences. -->
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="ZiggyCreatures.FusionCache.Backplane.Memory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CacheInvalidation.AppHost\CacheInvalidation.AppHost.csproj" />
    <ProjectReference Include="..\CacheInvalidation.WebApi\CacheInvalidation.WebApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
